In [8]:
import pandas as pd 
data=pd.read_csv('diabetics.csv') #datafram


data.shape
data.head()

# data.describe()

,a,b,c,d,e,f,g,h,I,j,k,l,m,n,o,p,q,r,s,outcome
0,1,1,22,22,22,19,18,14,49.895756,17.775994,5.270920,0.771761,0.018632,0.006864,0.003923,0.003923,0.486903,0.100025,1,0
1,1,1,24,24,22,18,16,13,57.709936,23.799994,3.325423,0.234185,0.003903,0.003903,0.003903,0.003903,0.520908,0.144414,0,0
2,1,1,62,60,59,54,47,33,55.831441,27.993933,12.687485,4.852282,1.393889,0.373252,0.041817,0.007744,0.530904,0.128548,0,1
3,1,1,55,53,53,50,43,31,40.467228,18.445954,9.118901,3.079428,0.840261,0.272434,0.007653,0.001531,0.483284,0.114790,0,0
4,1,1,44,44,44,41,39,27,18.026254,8.570709,0.410381,0.000000,0.000000,0.000000,0.000000,0.000000,0.475935,0.123572,0,1

In [11]:
# X = data.iloc[:, :-1]

X = data.drop('outcome' , 1)
Y = data[ 'outcome' ]

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix


rf = RandomForestClassifier(n_estimators = 10)

from sklearn.model_selection import KFold

k=5
kfold =KFold(n_splits=k, random_state=None, shuffle=False)

acclist=[]

for train_index, test_index in kfold.split(X):
    X_train , X_test = X.iloc[train_index,:],X.iloc[test_index,:]
    y_train , y_test = Y[train_index] , Y[test_index]
    rf.fit(X_train, y_train)
    predictions = rf.predict(X_test)
    
    from sklearn.metrics import confusion_matrix
    matrix = confusion_matrix(y_test, predictions)
    print( matrix )
    print('_________________________________________')
    
    
    from sklearn.metrics import accuracy_score
    acc=accuracy_score(y_test,predictions)
    acclist.append(acc)
    
acc=sum(acclist)/k
print('acc : ',acc)

C:\Users\youss\AppData\Local\Temp/ipykernel_7060/3116100262.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  X = data.drop('outcome' , 1)

[[74 29]
 [43 85]]
_________________________________________
[[77 30]
 [49 74]]
_________________________________________
[[76 33]
 [43 78]]
_________________________________________
[[72 35]
 [47 76]]
_________________________________________
[[77 37]
 [45 71]]
_________________________________________
acc :  0.6602710333145115